apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}-service
spec:
  type: NodePort
  selector:
    app: {{.Values.app}}
  ports:
    - port: {{.Values.port}}
      targetPort: {{.Values.port}}
      nodePort: {{.Values.nodePort}}